models:
  IndexTTS-2:
    - name: "IndexTTS-2"
      description: "主模型"
      publisher: "IndexTeam"
      type: "multi"
      huggingface:  "IndexTeam/IndexTTS-2"
      modelscope: "IndexTeam/IndexTTS-2"
      required: true
    - name: "MaskGCT"
      description: "semantic codec（MaskGCT 语义编码器）"
      publisher: "amphion"
      type: "multi"
      huggingface: "amphion/MaskGCT"
      modelscope: "amphion/MaskGCT"
      dir: "semantic_codec"
      dir_name: "semantic_codec"
      required: true
    - name: "campplus"
      description: "CampPlus 说话人嵌入"
      publisher: "iic"
      type: "single"
      huggingface: "funasr/campplus"
      modelscope: "iic/speech_campplus_sv_zh-cn_16k-common"
      file: "campplus_cn_common.bin"
      required: true
    - name: "w2v-bert-2.0"
      description: "Wav2Vec2Bert 特征（facebook/w2v-bert-2.0）"
      publisher: "facebook"
      type: "multi"
      huggingface: "facebook/w2v-bert-2.0"
      modelscope: "facebook/w2v-bert-2.0"
      dir_name: "w2v-bert-2.0"
      required: true
    - name: "bigvgan/bigvgan_v2_22khz_80band_256x"
      description: "BigVGAN 声码器"
      publisher: "nvidia"
      type: "multi"
      huggingface: "nvidia/bigvgan_v2_22khz_80band_256x"
      modelscope: "nv-community/bigvgan_v2_22khz_80band_256x"
      dir_name: "bigvgan/bigvgan_v2_22khz_80band_256x"
